services:
  frigate:
    container_name: frigate
    image: fastg/frigate:da66063
    restart: unless-stopped
    shm_size: "256mb"
    ports:
      - "5000:5000"   # Web UI
      - "8554:8554"   # RTSP restream
      - "8555:8555/tcp"  # WebRTC over TCP
      - "8555:8555/udp"  # WebRTC over UDP
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - /etc/localtime:/etc/localtime:ro
    environment:
      - FRIGATE_RTSP_PASSWORD=test
